apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registry.gitlab.com/bogdanbledea/no-pain-faculty:v15
        env:
          - name: "REACT_APP_TITLE"
            value: "No pain faculty | Development"
          - name: "REACT_APP_GRAPHQL_URL"
            value: "http://173.193.79.140:31234/graphql"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred